# fly.toml app configuration file generated for mercatorclimbers on 2024-10-04T16:28:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mercatorclimbers'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source="data"
  destination="/data"

[[vm]]
  size = 'shared-cpu-1x'
